# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harold Cheney
email: wscontact@haroldcheney.com
description: > # this means to ignore newlines until "baseurl:"
  My software, music, and whatever. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haroldcheney.com" # the base hostname & protocol for your site
twitter_username: haroldcheney
github_username:  haroldcheney

# Build settings
markdown: kramdown

collections:
  projects:
    output: false
  compositions:
    output: true
    permalink: /compositions/:path/
